export const TOGGLE_NAV_STATE = 'TOGGLE_NAV_STATE';

export const OPEN_RELEASE = 'OPEN_RELEASE';
export const CLOSE_RELEASE = 'CLOSE_RELEASE';

export const CLOSE_ERROR = 'CLOSE_ERROR';

export const COLLECTION_REQUEST = 'COLLECTION_REQUEST';
export const COLLECTION_SUCCESS = 'COLLECTION_SUCCESS';
export const COLLECTION_FAILURE = 'COLLECTION_FAILURE';

export const RELEASE_REQUEST = 'RELEASE_REQUEST';
export const RELEASE_SUCCESS = 'RELEASE_SUCCESS';
export const RELEASE_FAILURE = 'RELEASE_FAILURE';
